//
// Created by Farias, Karine on 3/17/21.
//

#ifndef SOCIALINEV2_SERVERNOTIFICATIONMANAGER_H
#define SOCIALINEV2_SERVERNOTIFICATIONMANAGER_H


class ServerNotificationManager {

};


#endif //SOCIALINEV2_SERVERNOTIFICATIONMANAGER_H
