//
// Created by Farias, Karine on 3/17/21.
//

#ifndef SOCIALINEV2_CLIENTNOTIFICATIONMANAGER_H
#define SOCIALINEV2_CLIENTNOTIFICATIONMANAGER_H


class ClientNotificationManager {

};


#endif //SOCIALINEV2_CLIENTNOTIFICATIONMANAGER_H
